version: '3.8'

services:
  db_sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    env_file:
      .env
    ports:
      - "8002:1433"
    volumes:
      - ./volumes/data:/var/opt/mssql/data
      - ./volumes/log:/var/opt/mssql/log
      - ./volumes/secrets:/var/opt/mssql/secrets
    restart: always
    networks:
      - backend

  server_app:
    build: .
    restart: always
    depends_on:
      - db_sqlserver
    env_file:
      - .env
    environment:
      - DATABASE_PUBLIC_URL=db_sqlserver
    ports:
      - "5500:5000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
